const GET_CATEGORY = 'GET_CATEGORY'
const GET_NAVS = 'GET_NAVS'
const GET_CONTENTS='GET_CONTENTS'
const GET_BRANDS = 'GET_BRANDS'
const GET_BRANDSCONTENT = 'GET_BRANDSCONTENT'
export {
    GET_CATEGORY,GET_NAVS,GET_CONTENTS,GET_BRANDS,GET_BRANDSCONTENT
}