const GET_HOME = 'GET_HOME'
const GET_NAV = 'GET_NAV'
const GET_TAB = 'GET_TAB'
const GET_HOMEPAGE = 'GET_HOMEPAGE'
const GET_BANNER = 'GET_BANNER'
const GET_NEWBEAUTY = 'GET_NEWBEAUTY'
const GET_NBMUYINGTOP = 'GET_NBMUYINGTOP'
const GET_NBGUOJITOP = 'GET_NBGUOJITOP'
const GET_JIADIAN = 'GET_JIADIAN'
const GET_JIAJU = 'GET_JIAJU'
const GET_LIFEMARKET = 'GET_LIFEMARKET'
const GET_LUX = 'GET_LUX'
export {
    GET_HOME,GET_NAV,GET_TAB,GET_HOMEPAGE,GET_BANNER,GET_NEWBEAUTY,GET_NBMUYINGTOP,GET_NBGUOJITOP,GET_JIADIAN,GET_JIAJU,GET_LIFEMARKET,GET_LUX
}